name: FreedomOPMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 5.2
description: A Minecraft plugin created for FreedomOP
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, Prozza, buildcarter8, SupItsDillon, Robo_Lord, Dragonfire147, cowgomooo12, Cyro1999, CrafterSmith12, tylerhyperHD]
